environment: "${APP_ENV}"

logging:
  level: debug 
  fileOutput:
    filePath: ""
    rotationPolicy: monthly
    maxSizeMB: 500
    maxBackups: 50

proxyConfig:
  httpPort: 
  httpsPort: 
  certFile: 
  keyFile: 
